// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgpb8jDKAqsjneOO9OAnMaIRNzvRC_omk',
    appId: '1:1001110228870:android:522cf5e76419003ecca607',
    messagingSenderId: '1001110228870',
    projectId: 'flutter-contacts-demo',
    databaseURL: 'https://flutter-contacts-demo-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-contacts-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaJ1eX9Ozq4ZLGWFp8S0r7bG8io3pn5WY',
    appId: '1:1001110228870:ios:0e1625dc2373b657cca607',
    messagingSenderId: '1001110228870',
    projectId: 'flutter-contacts-demo',
    databaseURL: 'https://flutter-contacts-demo-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-contacts-demo.appspot.com',
    iosBundleId: 'com.example.contactsV4',
  );
}
